### ISSUE TITLE
example 4 not working

### ISSUE THREAD

**Issue by trondhindenes** [dapr/samples#106]
I've tried to set up example 4 with a local redis, but it isn't working. Here's what I've done:
1. Everything is running in minikube. If used the "non-helm" setup, so everything is in the `default` namespace in my minikube cluster.
1. Added a redis deployment/service like so:
```
kind: Service
apiVersion: v1
metadata:
  name: redis-service
  labels:
    app: redis-service
spec:
  selector:
    app: redis-service
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service
  labels:
    app: redis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
      - name: redis-service
        image: redis
        command: ["redis-server", "--requirepass", "yourpassword"]
        ports:
        - containerPort: 6379
        imagePullPolicy: Always
```
configured the `redis.yml` file:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  metadata:
  - name: "redisHost"
    value: "redis-service.default.svc.cluster.local:6379"
  - name: "redisPassword"
    value: "yourpassword"
```
I've used `kubectl port-forward` to verify that the redis instance is indeed working using the specified password.

The react-app has problems when starting (output from the daprd sidecar):
```
time="2019-11-14T20:05:34Z" level=error msg="error getting topics from app: invalid character '<' looking for beginning of value"
time="2019-11-14T20:05:34Z" level=warning msg="failed to init actors: actors: state store must be present to initialize the actor runtime"

```
The other pods also log errors (output from the daprd sidecars):
```
time="2019-11-14T20:04:57Z" level=warning msg="failed to init actors: actors: state store must be present to initialize the actor runtime"
time="2019-11-14T20:04:57Z" level=info msg="http server is running on port 3500"
time="2019-11-14T20:04:57Z" level=info msg="gRPC server is running on port 50001"
time="2019-11-14T20:04:57Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 38.008444000000004ms"
```

as far as I can see there's very little health checking going on here (both in the apps and in dapr itself), giving the impression that everything is running as it should when in fact nothing is working.

I just cloned the samples repo just to see what dapr is about, apart from it looking like an interesting thing.
