### ISSUE TITLE
Sample 2 failing to persist state to Redis running in AKS cluster

### ISSUE THREAD

**Issue by lokijota** [dapr/samples#112]
## Expected Behavior

Sample application working correctly and persisting state to redis.

## Actual Behavior

a. In the logs of the pod I have:

```
kubectl logs --selector=app=node -c node
Got a new order! Order ID: 1157
Failed to persist state
Got a new order! Order ID: 1158
Failed to persist state
```

b. When I do a request to the URL:

```
curl  <my assigned ip>/order
{"errorCode":"ERR_STATE_STORE_NOT_FOUND","message":""}
```

c. I deployed everything as per instructions (or I think I did). Some more information:

- Using an AKS cluster
- Calling Dapr from Windows
- My running pods are (not all are related to dapr):
```
NAME                                     READY   STATUS    RESTARTS   AGE
brawny-pronghorn-redis-master-0          1/1     Running   0          17h
brawny-pronghorn-redis-slave-0           1/1     Running   0          17h
brawny-pronghorn-redis-slave-1           1/1     Running   0          17h
captureorder-894bbf6d7-j2677             1/1     Running   0          30d
captureorder-894bbf6d7-jzqr6             1/1     Running   6          26d
cert-manager-78dd8f6df8-hv9rq            1/1     Running   0          26d
dapr-operator-6b8d659466-5jvzw           1/1     Running   0          17h
dapr-placement-6494df4f78-4k2f5          1/1     Running   0          17h
dapr-sidecar-injector-588d69dc9b-dcfx2   1/1     Running   0          17h
frontend-5bbd877fd-rhcpc                 1/1     Running   0          30d
nodeapp-6cb765cb44-mj4g6                 2/2     Running   0          31m
orders-mongo-mongodb-ddfb9b977-rhpjz     1/1     Running   0          26d
pythonapp-559b6d55d6-x6k52               2/2     Running   0          25m
```

- My redis.yaml:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    value: <base64-decoded password here>
```

- I made no changes to node.yaml or python.yaml

## Steps to Reproduce the Problem

I just followed the instructions on the sample.
