### ISSUE TITLE
hello-docker-compose zipkin tracing not working

### ISSUE THREAD

**Issue by jp1482** [dapr/samples#55]
I want to trace call made by python app to node app. This is normally working when I do dapr from command prompt.
- I am using WSL2 for running docker. 

- Deployment of hello-docker-compose is success too. 

To add traceability I have added following thing in docker-compose. 

```
zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9412:9411"
    networks:
      - hello-dapr  
```

In components I have added following file. ( trace.yaml)

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: zipkin
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"
```
I am not able to see any tracing. 

To check that zipkin is available on specified endpointAddress , I did following things.

I have run ubuntu container in same hello-dapr network. Try to ping zipkin and it is working so container is there.

Another thing I did is manually load data to zipkin using curl and that also work successful. 

Now I am not getting that why python app to nodejs app communication is not traced. 

Am I missing something in configuration ?
