### ISSUE TITLE
dapr-apim-integration sample - echo-service and event-subscriber need a tracing config and fail to start

### ISSUE THREAD

**Issue by clarenceb** [dapr/samples#89]
echo-service and event-subscriber have the annotation:

```yaml
dapr.io/config: "tracing"
```

and fail to start as they can't find this config.

Fix:

* Create a tracing config in file `k8s/tracing.config.yaml`:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
```

```sh
kubectl apply -f k8s/tracing.config.yaml
```

Install Zipkin:

```sh
kubectl create deployment zipkin --image openzipkin/zipkin
kubectl expose deployment zipkin --type ClusterIP --port 9411
```

Redeploy echo-service and event-subscriber.
